CREATE TABLE accounts (
    id VARCHAR(48) NOT NULL PRIMARY KEY,
    report_time_zone VARCHAR NOT NULL,
    billing_currency VARCHAR NOT NULL,
    sys_language VARCHAR NOT NULL,
    domains_configuration VARCHAR NOT NULL,
    work_spaces  VARCHAR NOT NULL,
    fuel VARCHAR NOT NULL,
    conversion_registration_time_reporting VARCHAR NOT NULL,
    default_home_screen VARCHAR NOT NULL,
    default_way_to_open_report VARCHAR NOT NULL,
    ip_anonymization BOOLEAN NOT NULL,
    default_reporting_currency VARCHAR NOT NULL,
    profile_first_name VARCHAR NOT NULL,
    profile_last_name VARCHAR NOT NULL,
    primary_user VARCHAR NOT NULL,
    additional_users VARCHAR NOT NULL,
    skype VARCHAR NOT NULL,
    phone_number VARCHAR NOT NULL,
    two_factor_authentication VARCHAR NOT NULL,
    api_access_keys VARCHAR NOT NULL,
    billing_information VARCHAR NOT NULL,
    custom_conversions VARCHAR NOT NULL,
    referrer_handling_list VARCHAR NOT NULL,
    last_updated BIGINT NOT NULL
);