CREATE TABLE visits (
-- time with  nanos
    id BIGINT NOT NULL PRIMARY KEY,
    account_id VARCHAR(48) NOT NULL,
    campaign_id VARCHAR(48) NOT NULL,
    traffic_source_id VARCHAR(48) NOT NULL,
    funnel_id VARCHAR NOT NULL,
    pre_sell_landing_page_id VARCHAR NOT NULL,
    landing_page_ids VARCHAR NOT NULL,
    offer_ids VARCHAR NOT NULL,
    impressions_from_traffic_source VARCHAR NOT NULL,
    tracking_link_clicks VARCHAR NOT NULL,
    pre_landing_page_clicks VARCHAR NOT NULL,
    landing_page_clicks VARCHAR NOT NULL,
    offer_clicks VARCHAR NOT NULL,
    referrer VARCHAR NOT NULL,
    traffic_source_parameters VARCHAR NOT NULL,
    redirection_time VARCHAR NOT NULL,
    click_map VARCHAR NOT NULL,
    user_agent_data VARCHAR NOT NULL,
    geo_ip_data VARCHAR NOT NULL,
    conversions VARCHAR NOT NULL,
    custom_conversions VARCHAR NOT NULL,
    click_is_suspicious BOOL NOT NULL,
    last_updated BIGINT NOT NULL
);
